### ISSUE TITLE
Crashing when joining a occupied room

### ISSUE THREAD

**Issue by AllieLikesAstolfo** [Ricimon/FFXIV-ProximityVoiceChat#1]
Freshly installed plugin and only changed the I/O, I have been told there is _supposed_ to be a firewall prompt but no such prompt was given at installation for me. 
If I join a room and it's exclusively just me it will be fine, the moment I try to join a room with someone else already in it, it will instantly crash my game. 
I have not been able to test this when I am already in a room and a new user joins.
Reinstalling and manually deleting the XIVLauncher/installedPlugins/ folder did not work.
If there is a firewall exception required is there any where it is listed?

**Comment by AllieLikesAstolfo** [comment]
I just now got a friend to fresh install the plugin, and they were also not given this supposed firewall prompt multiple people have told me about.
We tested the 

> I have not been able to test this when I am already in a room and a new user joins.

and it still crashed for me but not the person with the fresh install.
I have tried enabling log printing but it is unable to print them due to the crashing

**Comment by AllieLikesAstolfo** [comment]
I went through and manually added FF14 to my firewall but this issue continues to be prevalent.
I added

- ffxivboot.exe
- ffxiv_dx11.exe

and so far this has not fixed it at all and it continues to crash when peering with another player.
Perhaps I'm missing something you have as an entry in your firewall?

**Comment by Ricimon** [comment]
I've gotten other reports of this crash behavior happening but I haven't been able to pinpoint the exact cause.

It seems one potential cause is having Voicemeeter on, but otherwise I'm still investigating this.

**Comment by AllieLikesAstolfo** [comment]
I pretty much nuked Voicemeeter and all it's drivers from my system but it still seems to be occurring.
I was able to use Chat 2 to see debug logs before it crashes and it's dying instantly on the addition of a new peer, if you would like, I have my logging set to debug right now but, I can go through and see what each type of logging displays?

**Comment by Ricimon** [comment]
Nah it's okay, I've gotten a bit more info on this. The crash is definitely occurring on initializing the peer connection, and it seems to have something to do with audio device settings on the system. It looks like it's a known issue that the version of the WebRTC library being used right now crashes on initialization when any unsupported audio devices are enabled on the system (even when it's not in-use), and I think Voicemeeter is an unsupported device. https://github.com/microsoft/MixedReality-WebRTC/pull/507 (this MR is merged but is not in the version used in this plugin right now)

I'll be working on a fix but for now try disabling other unused audio input/output devices you have on your system.

**Comment by Ricimon** [comment]
v0.2.1 (c833d3a09964567a9c2017adaf831b3c94e75093) should fix this issue.

**Comment by AllieLikesAstolfo** [comment]
Yep, worked without any hitches at all.
Haven't tried it with Voicemeeter reinstalled however, but regardless thanks for fixing!
